name: Plugin backtester

on:
  workflow_dispatch:
    inputs:
      backtest:
        description: 'Backtest to run'
        required: true
        type: string
        default: AAVEV2BUSD

      startBlock:
        description: 'Block to start backtesting from.'
        required: true
        type: number
        default: 15000000
      
      endBlock:
        description: The end block to backtest to. You can use '0' to use the latest block.
        required: true
        type: number
        default: 17590000

      stride:
        description: 'Number of blocks to go back from current block. Use 1 for accurate but slow tests, and higher numbers for fast estimates.'
        required: true
        type: number
        default: 1 # translates to 1 sample pr hour for mainnet
  
      
jobs:
  run_backtests:
    env:
      BACKTEST: ${{ inputs.backtest }}
      STRIDE: ${{ inputs.stride }}
      START_BLOCK: ${{ inputs.startBlock }}
      END_BLOCK: ${{ inputs.endBlock }}
      BACKTEST_SERVICE_URL: ${{ secrets.BACKTEST_SERVICE_URL }}
      MAINNET_RPC_URL: https://eth-mainnet.alchemyapi.io/v2/${{ secrets.ALCHEMY_MAINNET_KEY }}
      BACKTEST_RESULT_DIR: "backtests/"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn compile
      - run: yarn run:backtests
      - name: Archive backtest results
        uses: actions/upload-artifact@v3
        with:
          name: backtest-data
          path: backtests/